### ISSUE TITLE
when filtering by author, link to second page is not formed

### ISSUE THREAD

**Issue by oshipka** [YuriyLisovskiy/OOA_Team_XAEA#11]
When sending a request to page 2, receiving 404 instead of 200
https://github.com/YuriyLisovskiy/OOA_Team_XAEA/blob/f87a6213ab96854ffa02a72eefd3cd9f8ceb0b76/StudArt/tests/artwork/views/test_ArtworksAPIView.py#L54-L56
https://github.com/YuriyLisovskiy/OOA_Team_XAEA/blob/f87a6213ab96854ffa02a72eefd3cd9f8ceb0b76/StudArt/tests/artwork/views/test_ArtworksAPIView.py#L61-L63

**Comment by YuriyLisovskiy** [comment]
Look at `ArtworkSetPagination`:
https://github.com/YuriyLisovskiy/OOA_Team_XAEA/blob/f87a6213ab96854ffa02a72eefd3cd9f8ceb0b76/StudArt/artwork/pagination.py#L4-L8

You created 6 artworks for author `User` and you retrieve them all on the first page. So, there are not more pages with content and DRF don't create any link to the next or previous page, because you have only one page with data.

**Comment by YuriyLisovskiy** [comment]
You can try to add one more Artwork model to the database and check that DRF will generate two pages, the first one will contain 6 artworks and the second one will contain only one.
